org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.daemon=false

modID=hexcasting
modName=Hex Casting
modVersion=0.12.0-26.2

minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18.2
fabric_api_version=0.161.0+26.2
fabric_language_kotlin_version=1.14.1+kotlin.2.4.20
kotlin_version=2.4.20

cardinal_components_version=8.0.1
cloth_config_version=26.2.155+fabric
patchouli_version=26.1-94-beta
modmenu_version=20.0.3
